### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [ruhigundrelaxed/ioBroker.motion#12]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/ruhigundrelaxed/ioBroker.motion

- [ ] [E019] Invalid repository URL: https://github.com/ruhigundrelaxed/iobroker.motion.git. Expected: git+https://github.com/ruhigundrelaxed/ioBroker.motion.git
- [ ] [E104] No common.titleLang found in io-package.json
- [ ] [E109] desc in io-package.json should be an object for many languages. Found only Javascript/Node.js based motion adapter
- [ ] [E114] No adapter are allowed in the repo without admin3 support
- [ ] [E120] Unknown type found in io-package.json
- [ ] [E130] No news found in io-package.json
- [ ] [E150] No common.connectionType found in io-package.json
- [ ] [E152] No common.dataSource found in io-package.json
- [ ] [E140] width and height of logo are not equal
- [ ] [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.motion"
- [ ] [E300] Not found on travis. Please setup travis
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/ruhigundrelaxed/ioBroker.motion", press the settings button beside the about title and add some topics.
- [ ] [E603] NO "## Changelog" found in README.md
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2015-2022 ruhigundrelaxed<martin@qvadrat.de>" at the end of README.md

I have also found warnings that may be fixed if possible.

- [ ] [W113] Adapter should support compact mode
- [ ] [W400] Cannot find "motion" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by ruhigundrelaxed** [comment]
fixed e115, e119, e120

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
